/** Single permission matrix for command-level identity checks. */

import type { WorkspaceRole } from './entities.js';
import { roleAtLeast } from './command.js';

/**
 * Required role per command, generated from spec 03 §3 and the handlers that
 * already call `authorise`. A missing entry means "no role check" (first-run
 * and local-only maintenance). The same table drives the UI so the two cannot
 * drift. See docs/spec/03-commands-permissions.md §7.
 */
export const COMMAND_PERMISSIONS: Readonly<Record<string, WorkspaceRole>> = {
  CreateWorkspace: 'PLANNER',
  RenameWorkspace: 'PLANNER',
  SetWorkspaceTimezone: 'ADMIN',
  SetSizeMapping: 'PLANNER',
  MigrateFootprintUnits: 'PLANNER',
  SetDefaultReserves: 'PLANNER',
  SetTeamDefaults: 'PLANNER',
  SetTeamQuarterReserves: 'PLANNER',
  SetRuleThresholds: 'PLANNER',
  ResetRuleThresholds: 'PLANNER',
  SetChangeLoadSettings: 'PLANNER',
  SetGuardrails: 'PLANNER',
  SetValueDrivers: 'PLANNER',
  ResetSampleWorkspace: 'PLANNER',
  ArchiveWorkspace: 'PLANNER',
  RestoreWorkspace: 'PLANNER',
  DeleteWorkspace: 'ADMIN',
  SetNotificationSettings: 'PLANNER',
  SetWorkspaceRole: 'ADMIN',

  CreateTeam: 'PLANNER',
  RenameTeam: 'PLANNER',
  SetTeamDescription: 'PLANNER',
  SetTeamDefaultCapacity: 'PLANNER',
  ReorderTeams: 'PLANNER',
  ArchiveTeam: 'PLANNER',
  RestoreTeam: 'PLANNER',
  EnsureTeamQuarter: 'PLANNER',
  SetCapacityAdjustment: 'PLANNER',
  AddReserve: 'PLANNER',
  UpdateReserve: 'PLANNER',
  RemoveReserve: 'PLANNER',
  LinkIdeaToRefinementReserve: 'CONTRIBUTOR',
  UnlinkIdeaFromRefinementReserve: 'CONTRIBUTOR',
  AcceptOverflow: 'PLANNER',

  CreateIdea: 'CONTRIBUTOR',
  ImportIdeas: 'CONTRIBUTOR',
  RenameCommitment: 'CONTRIBUTOR',
  UpdateCommitment: 'CONTRIBUTOR',
  SetCommitmentClass: 'CONTRIBUTOR',
  SetImportance: 'CONTRIBUTOR',
  SetOwner: 'CONTRIBUTOR',
  SetPrimaryTeam: 'CONTRIBUTOR',
  SetTargetQuarter: 'CONTRIBUTOR',
  SetTargetDate: 'CONTRIBUTOR',
  SetLatestSafeStart: 'CONTRIBUTOR',
  SetAttentionDate: 'CONTRIBUTOR',
  SetNextAction: 'CONTRIBUTOR',
  SetOutcome: 'CONTRIBUTOR',
  SetCommitmentValueDrivers: 'CONTRIBUTOR',
  SetConfidence: 'CONTRIBUTOR',
  SetManagementNote: 'CONTRIBUTOR',
  SetCommitmentThemes: 'CONTRIBUTOR',
  PassCommitGate: 'PLANNER',
  RevertCommitGate: 'PLANNER',
  StartDelivery: 'PLANNER',
  CorrectToCommitted: 'PLANNER',
  HoldCommitment: 'PLANNER',
  ResumeCommitment: 'PLANNER',
  CompleteCommitment: 'PLANNER',
  DropCommitment: 'PLANNER',
  RenewCommitment: 'CONTRIBUTOR',
  SetRecurrence: 'CONTRIBUTOR',
  ArchiveCommitment: 'PLANNER',
  RestoreCommitment: 'PLANNER',
  DeleteCommitment: 'ADMIN',

  AssignCapacityFootprint: 'PLANNER',
  MoveCapacityFootprint: 'PLANNER',
  ResizeCapacityFootprint: 'PLANNER',
  SetFootprintConfidence: 'CONTRIBUTOR',
  SetPrimaryFootprint: 'PLANNER',
  RemoveCapacityFootprint: 'PLANNER',
  RestoreCapacityFootprint: 'PLANNER',
  SplitCapacityFootprint: 'PLANNER',
  MergeCapacityFootprints: 'PLANNER',

  CreateProductService: 'PLANNER',
  RenameProductService: 'PLANNER',
  ArchiveProductService: 'PLANNER',
  SetProductImpact: 'CONTRIBUTOR',
  RemoveProductImpact: 'CONTRIBUTOR',
  AddDependency: 'CONTRIBUTOR',
  SetDependencyType: 'CONTRIBUTOR',
  SetDependencyTarget: 'CONTRIBUTOR',
  SetDependencyOwner: 'CONTRIBUTOR',
  SetDependencyNeededBy: 'CONTRIBUTOR',
  SetDependencyStatus: 'CONTRIBUTOR',
  SetDependencyNote: 'CONTRIBUTOR',
  UpdateDependency: 'CONTRIBUTOR',
  RemoveDependency: 'CONTRIBUTOR',
  CreateDecision: 'CONTRIBUTOR',
  SetDecisionOwner: 'CONTRIBUTOR',
  SetDecisionNeededBy: 'CONTRIBUTOR',
  ResolveDecision: 'CONTRIBUTOR',
  ArchiveDecision: 'CONTRIBUTOR',
  AddMilestone: 'CONTRIBUTOR',
  UpdateMilestone: 'CONTRIBUTOR',
  SetMilestoneStatus: 'CONTRIBUTOR',
  RemoveMilestone: 'CONTRIBUTOR',
  CreateTheme: 'PLANNER',
  RenameTheme: 'PLANNER',
  ArchiveTheme: 'PLANNER',
  CreatePerson: 'CONTRIBUTOR',
  UpdatePerson: 'CONTRIBUTOR',
  ArchivePerson: 'CONTRIBUTOR',
  LinkPersonToUser: 'ADMIN',
  AddExternalLink: 'CONTRIBUTOR',
  UpdateExternalLink: 'CONTRIBUTOR',
  RemoveExternalLink: 'CONTRIBUTOR',

  ReviewSignal: 'VIEWER',
  SnoozeSignal: 'VIEWER',
  ClearSignalDisposition: 'VIEWER',
  CreateScenario: 'CONTRIBUTOR',
  RenameScenario: 'CONTRIBUTOR',
  CloneScenario: 'CONTRIBUTOR',
  DiscardScenario: 'CONTRIBUTOR',
  RecordScenarioCommand: 'CONTRIBUTOR',
  ShareScenario: 'CONTRIBUTOR',
  UpdateScenario: 'CONTRIBUTOR',
  RebaseScenario: 'CONTRIBUTOR',
  ApplyScenario: 'PLANNER',
  OpenQuarterReview: 'PLANNER',
  RecordQuarterOutcome: 'PLANNER',
  ProposeCarryOver: 'PLANNER',
  ConfirmCarryOver: 'PLANNER',
  CloseQuarter: 'PLANNER',
  ReopenQuarter: 'ADMIN',
  CreateSnapshot: 'PLANNER',
  DeleteSnapshot: 'PLANNER',
  RestoreSnapshot: 'PLANNER',
  SaveView: 'PLANNER',
  UpdateView: 'PLANNER',
  DeleteView: 'PLANNER',
  RemoveSavedView: 'PLANNER',
  ApplyImport: 'PLANNER',
  SaveImportMapping: 'PLANNER',
  RemoveImportMapping: 'PLANNER',
  ResolveSyncConflict: 'CONTRIBUTOR',
};

export function mayRunCommand(role: WorkspaceRole, commandName: string): boolean {
  const required = COMMAND_PERMISSIONS[commandName];
  return required === undefined || roleAtLeast(role, required);
}
